//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KimdolSoft.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class movimiento
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public movimiento()
        {
            this.abono = new HashSet<abono>();
            this.detallemovimiento = new HashSet<detallemovimiento>();
        }
    
        public int idMovimiento { get; set; }
        public System.DateTime fechaVenta { get; set; }
        public Nullable<System.DateTime> fechaEntrega { get; set; }
        public Nullable<int> descuento { get; set; }
        public Nullable<int> idCliente { get; set; }
        public string idEmpleado { get; set; }
        public int idTipoMovimiento { get; set; }
        public int valorTotal { get; set; }
        public string estado { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<abono> abono { get; set; }
        public virtual cliente cliente { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<detallemovimiento> detallemovimiento { get; set; }
        public virtual empleado empleado { get; set; }
        public virtual tipomovimiento tipomovimiento { get; set; }
    }
}
